
import PurchaseOrder from '../models/PurchaseOrder.js';
import Product from '../models/Product.js';
import { PDFDocument, StandardFonts } from 'pdf-lib';
import ExcelJS from 'exceljs';
export const listPOs = async (req,res)=>{ const items=await PurchaseOrder.find({}).populate('supplier').populate('items.product').sort({createdAt:-1}); res.json(items) };
export const createPO = async (req,res)=>{ const { supplier, items } = req.body; const total = (items||[]).reduce((s,it)=> s + Number(it.qty||0)*Number(it.unitCost||0), 0); const po=await PurchaseOrder.create({ supplier, items, total, status:'draft' }); res.status(201).json(po) };
export const getPO = async (req,res)=>{ const po=await PurchaseOrder.findById(req.params.id).populate('supplier').populate('items.product'); if(!po) return res.status(404).json({error:'not found'}); res.json(po) };
export const receivePartial = async (req,res)=>{ const po=await PurchaseOrder.findById(req.params.id); if(!po) return res.status(404).json({error:'not found'}); const { receipts=[] } = req.body; for(const r of receipts){ const it = po.items.find(x=> String(x.product)===String(r.product)); if(!it) return res.status(400).json({error:'Product not in PO'}); const qty=Number(r.qty||0); it.receivedQty=(it.receivedQty||0)+qty; await Product.findByIdAndUpdate(r.product,{ $inc:{ stockQty: qty } }) } const all = po.items.every(it=> (it.receivedQty||0)>=it.qty); po.status = all? 'received':'partially_received'; if(all) po.receivedAt=new Date(); await po.save(); res.json(po) };
export const receiptPdf = async (req,res)=>{ try{ const po = await PurchaseOrder.findById(req.params.id).populate('supplier').populate('items.product'); if(!po) return res.status(404).json({error:'PO not found'}); const pdf = await PDFDocument.create(); const page = pdf.addPage([595.28, 841.89]); const font = await pdf.embedFont(StandardFonts.Helvetica); let y = 800; const draw=(text,size=12,x=50)=>{ page.drawText(String(text),{x,y,size,font}); y-=size+6 }; draw('Buying Receipt',16); draw(`PO: ${po._id}`); draw(`Supplier: ${po.supplier?.name||''}`); draw(`Date: ${new Date(po.createdAt).toDateString()}`); draw(`Status: ${po.status}`); y-=6; draw('Items',14); draw('Name                           Qty    Unit Cost    Line Total',11); for(const it of po.items){ if(y<60){ y=800; pdf.addPage([595.28,841.89]) } const line = `${(it.product?.name||'').padEnd(30).slice(0,30)}  ${String(it.qty).padStart(4)}   Rs ${Number(it.unitCost).toFixed(2).padStart(8)}   Rs ${(Number(it.qty)*Number(it.unitCost)).toFixed(2)}`; draw(line,10) } y-=6; draw(`TOTAL: Rs ${Number(po.total).toFixed(2)}`,12); const bytes = await pdf.save(); res.setHeader('Content-Type','application/pdf'); res.setHeader('Content-Disposition',`inline; filename="buying_receipt_${po._id}.pdf"`); res.send(Buffer.from(bytes)); }catch(err){ res.status(400).json({error:'Could not build receipt PDF', details: err.message}) } };
export const receiptExcel = async (req,res)=>{ try{ const po = await PurchaseOrder.findById(req.params.id).populate('supplier').populate('items.product'); if(!po) return res.status(404).json({error:'PO not found'}); const wb = new ExcelJS.Workbook(); const ws = wb.addWorksheet('Buying Receipt'); ws.columns = [ {header:'Product', key:'name', width:30}, {header:'Qty', key:'qty', width:10}, {header:'Unit Cost (LKR)', key:'cost', width:18}, {header:'Line Total (LKR)', key:'total', width:20} ]; ws.addRow(['Supplier', po.supplier?.name||'']); ws.addRow(['PO', String(po._id)]); ws.addRow(['Date', po.createdAt.toISOString()]); ws.addRow([]); po.items.forEach(it=> ws.addRow({ name: it.product?.name||'', qty: it.qty, cost: it.unitCost, total: (Number(it.qty)*Number(it.unitCost)) })); ws.addRow([]); ws.addRow(['TOTAL', '', '', po.total]); res.setHeader('Content-Type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'); res.setHeader('Content-Disposition',`attachment; filename="buying_receipt_${po._id}.xlsx"`); await wb.xlsx.write(res); res.end(); }catch(err){ res.status(400).json({error:'Could not build receipt Excel', details: err.message}) } };
